from pydantic import BaseModel, Field


class PredictorBody(BaseModel):
    idade: int = Field(..., alias = "idade", description = "Idade")
    asma: int = Field(..., alias = "asma", description = "Asma")
    cardiopatia: int = Field(..., alias = "cardiopatia", description = "Cardiopatia")
    diabetes: int = Field(..., alias = "diabetes", description = "Diabetes")
    doenca_hematologica: int = Field(..., alias = "doenca_hematologica", description="Doença hematológica")
    doenca_hepatica: int = Field(..., alias = "doenca_hepatica", description="Doença Hepática")
    doenca_neurologica: int = Field(..., alias = "doenca_neurologica", description="Doença neurológica")
    doenca_renal: int = Field(..., alias = "doenca_renal", description="Doença renal")
    imunodepressao: int = Field(..., alias = "imunodepressao", description="Imunodepressão")
    obesidade: int = Field(..., alias = "obesidade", description="Obesidade")
    pneumopatia: int = Field(..., alias = "pneumopatia", description="Pneumopatia")
    puerpera: int = Field(..., alias = "puerpera", description="Puérpera")
    sindrome_de_down: int = Field(..., alias = "sindrome_de_down", description="Síndrome de Down")
    eh_racacor_amarela: bool = Field(..., alias = "eh_racacor_amarela", description="Raça/Cor amarela?")
    eh_racacor_branca: bool = Field(..., alias = "eh_racacor_branca", description="Raça/Cor branca?")
    eh_racacor_desconhecida: bool = Field(..., alias = "eh_racacor_desconhecida", description="Raça/Cor desconhecida?")
    eh_racacor_ignorada: bool = Field(..., alias = "eh_racacor_ignorada", description="Raça/Cor ignorada?")
    eh_racacor_indigena: bool = Field(..., alias = "eh_racacor_indigena", description="Raça/Cor indígena?")
    eh_racacor_nenhuma: bool = Field(..., alias = "eh_racacor_nenhuma", description="Raça/Cor nenhuma?")
    eh_racacor_parda: bool = Field(..., alias = "eh_racacor_parda", description="Raça/Cor parda?")
    eh_racacor_preta: bool = Field(..., alias = "eh_racacor_preta", description="Raça/Cor preta?")
    eh_covid_confirmado: bool = Field(..., alias = "eh_covid_confirmado", description="Covid confirmado?")
    eh_sexo_feminino: bool = Field(..., alias = "eh_sexo_feminino", description="Sexo feminino?")
    eh_sexo_indefinido: bool = Field(..., alias = "eh_sexo_indefinido", description="Sexo indefinido?")
    eh_sexo_masculino: bool = Field(..., alias = "eh_sexo_masculino", description="Sexo masculino?")
