from pydantic import BaseModel, Field


class PredictorBody(BaseModel):
    idade: int = Field(None, description = "Idade")
    asma: int = Field(None, description = "Asma")
    cardiopatia: int = Field(None, description = "Cardiopatia")
    diabetes: int = Field(None, description = "Diabetes")
    doenca_hematologica: int = Field(None, description="Doença hematológica")
    doenca_hepatica: int = Field(None, description="Doença Hepática")
    doenca_neurologica: int = Field(None, description="Doença neurológica")
    doenca_renal: int = Field(None, description="Doença renal")
    imunodepressao: int = Field(None, description="Imunodepressão")
    obesidade: int = Field(None, description="Obesidade")
    pneumopatia: int = Field(None, description="Pneumopatia")
    puerpera: int = Field(None, description="Puérpera")
    sindrome_de_down: int = Field(None, description="Síndrome de Down")
    eh_racacor_amarela: bool = Field(False, description="Raça/Cor amarela?")
    eh_racacor_branca: bool = Field(False, description="Raça/Cor branca?")
    eh_racacor_desconhecida: bool = Field(False, description="Raça/Cor desconhecida?")
    eh_racacor_ignorada: bool = Field(False, description="Raça/Cor ignorada?")
    eh_racacor_indigena: bool = Field(False, description="Raça/Cor indígena?")
    eh_racacor_nenhuma: bool = Field(False, description="Raça/Cor nenhuma?")
    eh_racacor_parda: bool = Field(False, description="Raça/Cor parda?")
    eh_racacor_preta: bool = Field(False, description="Raça/Cor preta?")
    eh_covid_confirmado: bool = Field(False, description="Covid confirmado?")
    eh_sexo_feminino: bool = Field(False, description="Sexo feminino?")
    eh_sexo_indefinido: bool = Field(False, description="Sexo indefinido?")
    eh_sexo_masculino: bool = Field(False, description="Sexo masculino?")
